name: 签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 22,14 * * *
  watch:
    types: started

jobs:
   
   build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Dependencies
       
     
      run: |
        pip install -r requirements.txt
         python index.py 
         python main.py
